export { default as Post } from './Post'
export { default as Category } from './Category'
export { default as AuthorInterface } from './Author'
export { default as ICommentForm } from './ICommentForm'
export { default as IComment } from './IComment'
